FirebaseExtended/firepad

lib/firepad.js
lib/rich-text-codemirror-adapter.js

Other user's selection can make the text hard to read especially on when CodeMirror is set to a "dark" theme. The other user's selection are often pastel and if the "dark" theme has very light font they blend together. 
I have made a styling adjust in `RichTextCodeMirrorAdapter.prototype.setOtherCursor` that adds transparency to the others user's selection so that it blends better with any background and still allows the text to be readable.

Add  transparency to "other user's" selections

---

README.md

This PR fixes the README instructions to find the html file in the test suite since no such basename `tests` exists it is `test`

README: fixed path for test suite

---

examples/firepad-userlist.js

Because the userlist does this on initialize:
```js
this.firebaseOn_(ref.root().child('.info/connected'), 'value', function(s) {
if (s.val() === true && self.displayName_) {
var nameRef = ref.child(self.userId_).child('name');
nameRef.onDisconnect().remove();
nameRef.set(self.displayName_);
}
});
```
Anytime the client reconnects, it will set its own name in Firebase to whatever `this.displayName_` is, even if the user has changed it post-initialize. Locally, this change won't be obvious to the user, because by default the input doesn't update, but other users will see the user reconnect with his or her old name (and be a bit confused about it).
I don't use this particular library personally anymore, but ran into this issue independently in my implementation, figure it'd be helpful to …

[userlist] Remember to set displayName_ on name change

---

examples/firepad.js
lib/text-pieces-to-inserts.js

insertHtmlAtCursor etc inserts a newline (\n) after every line including the last line. The newline after the last line should not be there.
This becomes important when trying to implement a paste html functionality using insertHtmlAtCursor  instead of the default CM paste. Pasting (inserting html) inside a line gets broken because you get an extra linebreak at the end that pushes the next letter to a new line.
This pull request changes firepad.textPiecesToInserts to not insert a newline after the last line. Also included is an updated examples\firepad.js so that this fix can be linked to from jsfiddle etc.

fix set html inserts extra new line at the end

---

package.json

This fixes compatibility with browserify: #231.

Exclude jsdom from browserify builds

---

lib/ace-adapter.coffee

A few lines above, we're binding the focus event to `onFocus`, but here, the original author is unbinding `onCursorActivity` from the focus event, which means `onFocus` never gets unbound! This commit fixes that.

Fix a leak caused by a typo from 2013

---

package.json

This updates `package.json` to allow firebase versions ^3 and ^4. Firebase 4.0.0 was released on May 17, 2017. Projects which are using firebase _and_ firepad will benefit from this: When bundling an app using both firebase and firepad, firepad will not come with its own bundled copy of the firebase library, instead they can use a shared copy of firebase with a version pegged by the project consuming firepad.

Include firebase ^4 in acceptable version range

---

lib/monaco-adapter.js

When monaco was not using '\n' as its line ending then the calculations for text positions where all incorrect which caused the creation of faulty TextOps
This simply uses the monaco.getModel().getEOF() to access the currently used line feed and calculate positions based on that.

Changed monaco-adapter to respect line endings

---

changelog.txt
lib/monaco-adapter.js
package-lock.json
package.json

This should fix when receiving multiple arguments in the monaco editor change handler. Related issue: https://github.com/FirebaseExtended/firepad/issues/305
To reproduce the error: 
1. enter some characters
2. select few characters
3. type `{` then it will receive an error in the console

Accept multiple arguments in monaco editor change handler

---

changelog.txt
examples/monaco.html

Enable comment feature in example/monaco.html
Step to use this feature:
1. Type some characters
2. Select the line 
3. Press `Cmd+/`

Enable comment feature in example/monaco.html

---

lib/monaco-adapter.js
test/index.html
test/karma.conf.js
test/specs/monaco-ops.spec.js

Fixes bugs in the Monaco adapter.
(1) Selecting multiple lines and pressing "tab" causes collaborators to merge changes incorrectly.
(2) Selecting multiple lines and commenting them out causes collaborators to merge changes incorrectly.
Both changes are related to the handling of batched operations.
This PR is a minimized version of #325 that omits changes in the overall design of the file. Relies on `monacoModel.getPositionAt` instead of `posFromIndex` and `indexFromPos`.
N/A
jbchavez19 signed one for our organization for a previous PR.

Fix incorrect offset handling in Monaco adapter.

---

lib/monaco-adapter.js
test/specs/monaco-ops.spec.js

Created only those APIs that are been called either by
Firepad or EditorClient.
Syncing between editors and cursors.
Updated package-lock, found 7 vulnerability with breaking
change update
Removed depenencies and function prototypes created while
transpiling from Coffescript code for Ace. Rewritten specific to
Monaco Editor and it's API standards.
Add Build task to convert ES6+ codes into ES5 using Babel.
Add Testcases to verify changes from Monaco editor onChange
event handler to OT.js Text Operations.
Ref: #324 
Closes: #313 
Signed-off-by: Progyan Bhattacharya <Progyan@hackerrank.com>

Monaco Adapter: Rewrite from scratch in ES6+

---

lib/headless.js

I think the 'key' variable is an unexpected global variable.
It would be better to declare it with 'var'.
N/A

Fix a incorrect global variable as a local variable

---

lib/headless.js

PR to solve Issue #332 
I tested manually, it was not trivial for me add a new test to test Headless.prototype.initializeFakeDom function.

Fix headless jsdom version ^12.2.0

---

examples/security/validate-auth.json

Fixing issues with the example authentication JSON. A random key ID is sent to the database that needs to be permitted.

Fixed auth example JSON

---

Gruntfile.js
package-lock.json
package.json

* Coffeescript 2 outputs latest ES6 code. So use babel
to transpile to ES5
Since version 1.5.2, the build file contains `class ACEAdapter` as coffeescript version was bumped to 2.x. This does not work well with bower/rails integration. So to fully transpile it to ES5, I have added babel.

Transpile coffee files through babel

---

test/specs/integration.spec.js

This is based on https://github.com/FirebaseExtended/firepad/pull/339 but I have tweaked the ordering so we wait for the first firepad to sync before initializing the 2nd one at all, since the test is meant to verify that when the 2nd one does initialize, it does not use the default text.

Fix failing test for 'defaultText'

---

lib/monaco-adapter.js

Currently, we are getting the below error with the latest versions of monaco-editor and firebase:
typeError: Right-hand side of 'instanceof' is not callable
new t
node_modules/firepad/dist/firepad.min.js:1345
1342 | },
1343 | o = function () {
1344 | function t(t) {
The issue has also been reported by another user here: https://github.com/FirebaseExtended/firepad/commit/e39b4c147d6f41a246cb56232a0d6fc33833fd59

Fix incompatibility issue with monaco-editor

---

lib/firebase-adapter.js
test/specs/integration.spec.js

Bug Fix.
Firepad waits until it is ready to dispose. This results in Firepad throwing an error, and updating  the code editor with content before destroying.
This fixes that behavior by removing the callbacks from the destroyed instance, and making the function which updates the code editor a no-op before the instance is. in a ready state.

Immediately stop handling revision and callbacks

---

lib/firepad.js

Bug fix: `Firepad.prototype.setText` would overwrite the inline styles of the codemirror wrapper element by calling `setAttribute('style', 'display: none')` instead of `style.display = "none"`.
N/A

Don't clear CodeMirror inline styles on setText
